{% set name = "py-rattler-build" %}
{% set version = "0.65.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: 896468793a45747b7ac1f860196432d9d57ded413ac4aceb9e76a06431ce186f

build:
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make  # [unix]
  host:
    - pip
    - python
    - maturin >=1.11,<2
    - openssl {{ openssl }}  # [unix]
  run:
    - python

test:
  imports:
    - rattler_build
    - rattler_build._rattler_build
  requires:
    - pip
  commands:
    - pip check
    - python -c "from rattler_build import rattler_build_version; assert rattler_build_version()"

about:
  home: https://rattler.build
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The fastest way to build conda packages programatically
  description: |
    The `rattler-build` tooling and library creates cross-platform relocatable
    binaries / packages from a simple recipe format. The recipe format is heavily
    inspired by `conda-build` and `boa`, and the output of a regular `rattler-build`
    run is a package that can be installed using `mamba`, `rattler` or `conda`.
  dev_url: https://github.com/prefix-dev/rattler-build
  doc_url: https://rattler.build/latest/py-rattler-build/reference

extra:
  feedstock-name: py-rattler-build
  recipe-maintainers:
    - baszalmstra
    - pavelzw
